using UnityEngine;
using UnityEngine.UI;

public class KillboxGame : MonoBehaviour
{
    Canvas canvas; Transform root; GameObject world, player; Camera cam;
    string alias = "SUPERVIVIENTE"; int selected; int box = 2000; int stars;
    string[] chars = { "REX", "LUNA", "MAX", "MAYA", "KAI" };
    string[] jobs = { "MECANICO", "DETECTIVE", "EXPLORADOR", "MEDICA", "MENSAJERO" };
    string[] bios = { "Conoce Nova City y convierte el entorno en una ventaja.", "Observa, rastrea y espera el momento exacto.", "Encuentra recursos y prepara emboscadas.", "Resiste bajo presion y recupera vida.", "Rapido, impredecible y dificil de atrapar." };
    string[] skills = { "BARRICADA: coloca cobertura temporal.", "RASTRO: revela huellas cercanas.", "TRAMPA: deja un dispositivo oculto.", "CURACION: recupera parte de la vida.", "TURBO: aumenta la velocidad unos segundos." };

    void Awake(){ Application.targetFrameRate=60; Screen.orientation=ScreenOrientation.LandscapeLeft; MakeCanvas(); Alias(); }
    void MakeCanvas(){ var g=new GameObject("KILLBOX UI",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)); canvas=g.GetComponent<Canvas>(); canvas.renderMode=RenderMode.ScreenSpaceOverlay; var s=g.GetComponent<CanvasScaler>(); s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize; s.referenceResolution=new Vector2(1280,720); root=new GameObject("Root").transform; root.SetParent(canvas.transform,false); }
    void Clear(){ foreach(Transform t in root) Destroy(t.gameObject); }
    Text T(Transform p,string x,int n){ var g=new GameObject("Text",typeof(Text)); g.transform.SetParent(p,false); var t=g.GetComponent<Text>(); t.text=x; t.font=Resources.GetBuiltinResource<Font>("Arial.ttf"); t.fontSize=n; t.color=Color.white; return t; }
    Button B(Transform p,string x,UnityEngine.Events.UnityAction a){ var g=new GameObject("Button",typeof(Image),typeof(Button)); g.transform.SetParent(p,false); g.GetComponent<Image>().color=new Color(.05f,.10f,.12f,.98f); var b=g.GetComponent<Button>(); b.onClick.AddListener(a); T(g.transform,x,24).alignment=TextAnchor.MiddleCenter; return b; }
    RectTransform Page(string title,string sub){ var g=new GameObject("Page",typeof(Image)); g.transform.SetParent(root,false); var r=g.GetComponent<RectTransform>(); r.anchorMin=Vector2.zero; r.anchorMax=Vector2.one; r.offsetMin=r.offsetMax=Vector2.zero; g.GetComponent<Image>().color=new Color(.015f,.025f,.035f,1); T(g.transform,"KILLBOX",34); T(g.transform,title,46); T(g.transform,sub,20); return r; }
    void Alias(){ Clear(); var p=Page("NOVA CITY","CREATE YOUR IDENTITY"); T(p,"CHOOSE YOUR ALIAS",30); var b=B(p,"CONTINUE",Character); b.GetComponent<RectTransform>().sizeDelta=new Vector2(480,80); b.GetComponent<RectTransform>().anchoredPosition=new Vector2(0,-180); }
    void Character(){ Clear(); var p=Page("CHOOSE YOUR SURVIVOR","Every character has a different strategy."); T(p,chars[selected]+"  -  "+jobs[selected],42); T(p,bios[selected],25); T(p,skills[selected],24); var l=B(p,"<",()=>{ selected=(selected+4)%5; Character(); }); l.GetComponent<RectTransform>().sizeDelta=new Vector2(100,80); l.GetComponent<RectTransform>().anchoredPosition=new Vector2(-500,-100); var n=B(p,">",()=>{ selected=(selected+1)%5; Character(); }); n.GetComponent<RectTransform>().sizeDelta=new Vector2(100,80); n.GetComponent<RectTransform>().anchoredPosition=new Vector2(500,-100); var c=B(p,"CHOOSE CHARACTER",Lobby); c.GetComponent<RectTransform>().sizeDelta=new Vector2(420,80); c.GetComponent<RectTransform>().anchoredPosition=new Vector2(0,-220); }
    void Lobby(){ Clear(); var p=Page("NOVA CITY","YOUR BASE"); T(p,alias+"     STARS "+stars+"     BOX "+box,30); T(p,"SURVIVOR  -  "+chars[selected]+" / "+jobs[selected],34); T(p,"NEXT EVENT",24); T(p,"NIGHT CITY  -  22:00  -  UP TO 100 PLAYERS  -  30s CYCLES",27); var play=B(p,"PLAY NOW",Match); play.GetComponent<RectTransform>().sizeDelta=new Vector2(650,95); play.GetComponent<RectTransform>().anchoredPosition=new Vector2(0,-120); var inv=B(p,"INVENTORY",()=>Info("INVENTORY","Clothes, weapons and equipment.")); inv.GetComponent<RectTransform>().sizeDelta=new Vector2(220,65); inv.GetComponent<RectTransform>().anchoredPosition=new Vector2(-390,-260); var shop=B(p,"SHOP",()=>Info("SHOP","Strategy equipment and customization.")); shop.GetComponent<RectTransform>().sizeDelta=new Vector2(220,65); shop.GetComponent<RectTransform>().anchoredPosition=new Vector2(-130,-260); var set=B(p,"SETTINGS",()=>Info("SETTINGS","Sound, music, vibration and quality.")); set.GetComponent<RectTransform>().sizeDelta=new Vector2(220,65); set.GetComponent<RectTransform>().anchoredPosition=new Vector2(130,-260); }
    void Info(string title,string body){ Clear(); var p=Page(title,"KILLBOX"); T(p,body,28); var b=B(p,"BACK",Lobby); b.GetComponent<RectTransform>().sizeDelta=new Vector2(300,70); b.GetComponent<RectTransform>().anchoredPosition=new Vector2(0,-220); }
    void Match(){ Clear(); BuildWorld(); var p=Page("NOVA CITY","SURVIVAL  -  CYCLE 30s"); p.GetComponent<Image>().color=new Color(0,0,0,0); T(p,"HP 100     PLAYERS 100     TIME 30",28); var a=B(p,"ATTACK",()=>{}); a.GetComponent<RectTransform>().sizeDelta=new Vector2(220,90); a.GetComponent<RectTransform>().anchoredPosition=new Vector2(430,-240); var h=B(p,"ABILITY",()=>{}); h.GetComponent<RectTransform>().sizeDelta=new Vector2(220,90); h.GetComponent<RectTransform>().anchoredPosition=new Vector2(180,-240); }
    void BuildWorld(){ world=new GameObject("NovaCity"); var ground=GameObject.CreatePrimitive(PrimitiveType.Plane); ground.transform.SetParent(world.transform); ground.transform.localScale=new Vector3(8,1,8); ground.GetComponent<Renderer>().material.color=new Color(.08f,.1f,.11f); for(int i=0;i<32;i++){ float x=(i%8-4)*9; float z=(i/8-2)*12; var b=GameObject.CreatePrimitive(PrimitiveType.Cube); b.transform.SetParent(world.transform); b.transform.position=new Vector3(x,2,z); b.transform.localScale=new Vector3(6,4,8); b.GetComponent<Renderer>().material.color=new Color(.16f,.2f,.22f); } player=GameObject.CreatePrimitive(PrimitiveType.Capsule); player.name="Player"; player.transform.position=new Vector3(0,1,0); player.GetComponent<Renderer>().material.color=new Color(.25f,1f,.7f); cam=new GameObject("ThirdPersonCamera",typeof(Camera)).GetComponent<Camera>(); cam.transform.position=new Vector3(0,7,-9); cam.transform.LookAt(player.transform); }
}
